### ISSUE TITLE
Can’t install in macOS Sierra

### ISSUE THREAD

**Issue by stephenwade** [bartobri/no-more-secrets#36]
Here is a gist with the command-line output of `brew install -v no-more-secrets` (`nms.log`) and the log from make (`01.make`):

https://gist.github.com/de65d87dceed4ba87f66ba8fe059b1da

**Comment by bartobri** [comment]
Hmmm... Couple things.

Sierra isn't officially released yet. Once released, the homebrew maintainers may need some time to iron out installation issues caused by the upgrade.

If after a week or two the installation is still failing on Sierra, after making sure your version of homebrew is updated, open an issue with the Homebrew/homebrew-core project. This is the project responsible for the no-more-secrets port on Mac.

Placing this issue on hold for now.

**Comment by bartobri** [comment]
Labeling as invalid and holding for now until port maintainers have had some time with Sierra.

**Comment by stephenwade** [comment]
Got the problem solved (Homebrew/homebrew-core#5080). Thanks!

**Comment by stephenwade** [comment]
In case anyone else comes by wondering about this, the problem was that I didn't have the command-line tools installed. `sudo xcode-select --install` installed the tools and fixed the problem.
