### ISSUE TITLE
Provide release binaries on github

### ISSUE THREAD

**Issue by serpro69** [bartobri/no-more-secrets#89]
Hi,

Would be nice to be able to download binaries for `nms` and `sneakers` from github instead of building from source.

Thanks.

**Comment by bartobri** [comment]
Hello! Thanks for the interest!

This project only supports linux and unix systems. On these systems, building from source is free and trivial. The instructions are provided. Windows systems are not supported since this project leverages unix-only OS features. Windows users can still install this program inside of WSL (Windows subsystems for Linux).

Thanks,
Brian
